### ISSUE TITLE
As a developer, I would like to track user's mental state so we can to track users' progress over time and contact emergency contacts if necessary.

### ISSUE THREAD

**Issue by beratyavas19** [BIL496-SCPFoundation/psybotic-server#7]
In this component we will track the psychological status of a user as a result of the conversations of the users in different periods. During the periodic conversations with the user. If the user's mental state doesn't improve after a while, this component will contact the user's emergency contact (via Email) and will inform user to see a psychologist.

**Comment by Lumpus99** [comment]
Implemented as mental state tracking
